-- Table d'audit et de suivi de tous les paiements initiés (Paynote, Maviance, etc.)
CREATE TABLE IF NOT EXISTS `payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `references` VARCHAR(120) NOT NULL,
  `gateway` VARCHAR(30) NOT NULL DEFAULT 'paynote',
  `operateur` VARCHAR(20) NOT NULL,
  `numero_telephone` VARCHAR(30) NOT NULL,
  `montant` DECIMAL(15,2) NOT NULL,
  `statut` ENUM('initiated', 'pending', 'complete', 'failed', 'cancelled') NOT NULL DEFAULT 'initiated',
  `provider_message_id` VARCHAR(128) NULL,
  `provider_status` VARCHAR(60) NULL,
  `type_operation` VARCHAR(50) NOT NULL DEFAULT 'versement',
  `idcompte` INT NULL,
  `idclient` INT NULL,
  `iduser` INT NULL,
  `description` TEXT NULL,
  `message_erreur` TEXT NULL,
  `request_payload` LONGTEXT NULL,
  `response_payload` LONGTEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payment_references` (`references`),
  KEY `idx_payment_provider_message_id` (`provider_message_id`),
  KEY `idx_payment_operateur` (`operateur`),
  KEY `idx_payment_statut` (`statut`),
  KEY `idx_payment_idclient` (`idclient`),
  KEY `idx_payment_idcompte` (`idcompte`),
  KEY `idx_payment_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
